### PR TITLE
Allow not using discovery

### PR DESCRIPTION
**Pull request by bfayers**
This may not be the best way of not using discovery, but it works perfectly fine.

### CODE REVIEW

**Comment by gpbenton** [comment]
There is a potential problem with this.  

Some other routines assume that when they get a urllib exception it is because the IP address of the box has changed, so it tries to delete the serial_number entry from deviceURL[] and look up the address again.  This is no longer appropriate if the ip address was entered directly.

In that case, the correct thing to do is re-raise the urllib exception.

Is there some reason you need to do this?  Is the discovery not working properly?

**Comment by bfayers** [comment]
Yeah, the discovery flat out refused to function on my network.
 
If its of any reference:
Virginmedia Superhub3 in router mode
TP-Link PL-AC56 acces point  over homeplug

**Comment by gpbenton** [comment]
I can see a lot of conditions being added to handle this within the existing structure, which wouldn't look pretty.  

I have been thinking of taking a more object oriented approach to the project, and overloading the id would be a perfect excuse to it.  I should get a chance to look in to this some time this week.

**Comment by gpbenton** [comment]
I have created an object oriented version in the branch objectify.  Usage is along the lines

```python
from freesat import Freesat
p = Freesat("192.168.0.3:1234")
p.getChannelList()
```

You can use ipaddress and port as the id, or the serial number, although the port seems to change so I am not sure how useful this is going to be in practice.

**Comment by bfayers** [comment]
Thanks! this looks like a good option!

**Comment by gpbenton** [comment]
There are timeout and repeat options to the ssdp.discovery routine.  You might try changing those to see if you have any success.

And if that fails, I have no problems changing the library if you find one that works better for you.  But I couldn't tell as this one works fine for me.

**Comment by bfayers** [comment]
@gpbenton I don't think my network likes self discovery _at all_ the apps can find the box fine, even `gssdp-discover` cant find the box.

**Comment by bfayers** [comment]
I have a small code snippet that can resolve the port change @gpbenton 

Requirements: https://pypi.python.org/pypi/python-nmap

Code:
```
import nmap
nm = nmap.portScanner()
ip = input("IP: ")
nm.scan(ip, arguments='-p-')
all_tcp = nm[ip].all_tcp()
port = all_tcp[1] #Always seems to be the second in the array because first is 53  (why does it run dns??)
final_ip = ip+port
```

Integrate this however, now all we need is a home-assistant component

**Pull request closed without merging**
